---
functional:
  - Пользователь должен иметь возможность играть с любым человеком, с ботом или другом (доступ по ссылке)
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока. 
  - Внутри игры оба игрока должны видеть друг у друга редактор с кодом, вывод тестов, могут иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность выбирать уровень сложности игры
  - Завершенная игра должна быть доступна в записи для повторного просмотра
  - Задачи должны быть доступны на двух языках — русском и английском
  - На сайте должен быть чат, в котором могут общаться зарегистрированные пользователи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Чат для общения пользователей должен иметь проверку текста на оскорбительные выражения
