---
functional:
  - Пользователь должен иметь возможность играть с любым человеком, с ботом или другом (доступ к лобби по ссылке)
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока. 
  - Внутри лобби оба игрока должны видеть друг у друга редактор с кодом, вывод тестов, могут иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность выбирать уровень сложности игры
  - Пользователи должны получать очки за игры, на основе которых строится рейтинг за неделю, месяц и за все время
  - Другие пользователи должны иметь возможность следить за ходом игры, в которой не участвуют
  - Завершенная игра должна быть доступна в записи для повторного просмотра
  - Задачи должны быть доступны на двух языках — русском и английском
  - На сайте должен быть чат, в котором могут общаться зарегистрированные пользователи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Чат для общения пользователей должен иметь проверку текста на оскорбительные выражения
